### ISSUE TITLE
`flask run` produces `Error: Could not import "server"`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#1]
I just updated openfisca-uk, and followed the instructions to run:
```
(base) mghenis@penguin:~/nikhilwoodruff/openfisca-uk-ui$ export FLASK_APP=server/server.py
(base) mghenis@penguin:~/nikhilwoodruff/openfisca-uk-ui$ flask run
 * Serving Flask app "server/server.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "server".
```

**Comment by nikhilwoodruff** [comment]
Hmm- I'll change the read me if this works- sorry, could you try instead:

cd server
export FLASK_APP=server.py
flask run

The original instructions worked on my machine, but hopefully this works for you too.

**Comment by MaxGhenis** [comment]
Oops this was actually because I couldn't merge because my clone was pointing to the old `openfisca-uk-ui-client` repo
