### ISSUE TITLE
Universal Credit and Housing Benefit reforms show incorrect results

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#141]
[This reform](https://uk.policyengine.org/population-results?child_UBI=9&adult_UBI=9&senior_UBI=9&abolish_UC=1) replaces UC with a budget-neutral UBI. This should be almost entirely a net gain for high-income households, but PolicyEngine shows that 38% of the top decile come out behind. @nikhilwoodruff found that 5 of ~3,000 households in the top decile receive UC.

![image](https://user-images.githubusercontent.com/6076111/131748909-54c962e7-c2d2-475b-8869-0c9d85211c34.png)

**Comment by MaxGhenis** [comment]
Here are the results from [just abolishing UC](https://uk.policyengine.org/population-results?abolish_UC=1):
![image](https://user-images.githubusercontent.com/6076111/131756682-9971dad4-3dda-419f-a141-026157b20ce6.png)

The results from a [1 pound PA - AutoUBI](https://uk.policyengine.org/population-results?personal_allowance=1&child_UBI=29&adult_UBI=29&senior_UBI=29) are basically identical to the cached [PA repeal - AutoUBI](https://uk.policyengine.org/population-results?personal_allowance=0&child_UBI=29&adult_UBI=29&senior_UBI=29), which matches our report, so I don't think there's any broader issue.

**Comment by nikhilwoodruff** [comment]
I checked openfisca-uk via the Python interface, and I think it's an issue somewhere between the outputs of the model and the graph: in the top decile, 5 households (out of ~1300) have Universal Credit, and they're all households with between 2 and 3 benefit units (this makes sense, because income is assessed at the benefit unit level).

**Comment by MaxGhenis** [comment]
Fixed in #162 and pslmodels/openfisca-uk#196
