### ISSUE TITLE
Use policy parameters as of today's date

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#151]

**Comment by MaxGhenis** [comment]
Setting this to Oct 6, when the UC uplift ends.

**Comment by nikhilwoodruff** [comment]
Just had a thought - I think the best way to do this might be to make a function in `openfisca-uk`: f(date) -> Reform which takes the policy values at the date, and overwrites everything in the year with those.

**Comment by MaxGhenis** [comment]
Fixed in #175. Removing the other issues from this epic which can be separated.
