### ISSUE TITLE
Add table breaking down a household's net income by component for baseline and reform 

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#157]
e.g.:

| Component       | Baseline | Reform | Change | %      |
| --------------- | -------- | ------ | ------ | ------ |
| Net income      | 19000    | 21000  | 2000   | 10.5%  |
| \+ Gross income | 20000    | 20000  | 0      | 0.0%   |
| \+ Taxes        | \-3000   | \-4000 | \-1000 | 33.3%  |
| \+ Benefits     | 2000     | 5000   | 3000   | 150.0% |

which could expand to

| Component              | Baseline | Reform | Change | %        |
| ---------------------- | -------- | ------ | ------ | -------- |
| Net income             | 36000    | 37000  | 1000   | 2.8%     |
| \- Gross income        | 20000    | 20000  | 0      | 0.0%     |
| Employment income      | 19500    | 19500  | 0      | 0.0%     |
| Dividends              | 500      | 500    | 0      | 0.0%     |
| \- Taxes               | \-3000   | \-4000 | \-1000 | 33.3%    |
| Income tax             | \-2300   | \-3900 | \-1600 | 69.6%    |
| National Insurance     | \-650    | 0      | 650    | \-100.0% |
| Dividend tax           | \-50     | \-100  | \-50   | 100.0%   |
| \- Benefits            | 2000     | 5000   | 3000   | 150.0%   |
| Universal Credit       | 2000     | 0      | \-2000 | \-100.0% |
| Universal Basic Income | 0        | 5000   | 5000   | \-       |

**Comment by nikhilwoodruff** [comment]
It'd be really nice to have this generated procedurally from the entire computation tree, perhaps with a depth limit.

**Comment by MaxGhenis** [comment]
Duplicate of https://github.com/PolicyEngine/policyengine/issues/128
