### ISSUE TITLE
Automatically set defaults to policy parameters

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk-old#177]
From [this code](https://github.com/UBICenter/policyengine-uk/pull/175#discussion_r703803278) - the `default_policy.js` should fetch from openfisca-uk.

**Comment by MaxGhenis** [comment]
Bumping this up as it would have avoided #252 (plus it's a pain as we have a number of new parameters we want to add)

**Comment by nikhilwoodruff** [comment]
This is now done - handled via the `/api/parameters` endpoint.
