### ISSUE TITLE
Use round numbers for x axis on net income and MTR charts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#280]
This is one of the last charting weirdnesses so adding to the sprint. This should use increments of 100 (we don't want to just round the chart, it should be in the data).

![image](https://user-images.githubusercontent.com/6076111/135648430-6b58fce4-d44d-4147-9ad2-351aefb12d83.png)

I don't think there's anything to do in PolicyEngine, but filing here for visibility. Work is in https://github.com/PolicyEngine/openfisca-uk/issues/160

**Comment by nikhilwoodruff** [comment]
This is now fixed - the step size is £100.
