### ISSUE TITLE
Round budgetary impacts to full billions (not tens of billions)

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#292]
Currently if a reform produces e.g. a 212bn net cost, it's shown (in both the headline numbers and the waterfall chart) as 210bn

This is a rdbl issue

**Comment by MaxGhenis** [comment]
[Here's a problematic example](https://uk.policyengine.org/population-results?personal_allowance=0): 110-6=100
![image](https://user-images.githubusercontent.com/6076111/136643419-42af2e86-db81-4f23-a80b-086f3bf6467d.png)
![image](https://user-images.githubusercontent.com/6076111/136643430-a3d59fcd-9bbb-45fc-9d73-030ac1243473.png)
![image](https://user-images.githubusercontent.com/6076111/136643435-b1e00c5c-e220-4e0f-a731-4dad08901e6c.png)

@nikhilwoodruff could you take a crack at this in the next couple days? We can do the Resilience UBI post on Monday but I'd like to have this sorted first.

**Comment by nikhilwoodruff** [comment]
We now round to 3 significant figures, so closing.
