### ISSUE TITLE
Specify units and period in "About you" boxes

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#33]
e.g. this

![image](https://user-images.githubusercontent.com/6076111/129834977-97fdbf36-4f32-4de6-906f-456adac7401b.png)

should look like
![image](https://user-images.githubusercontent.com/6076111/129835023-e5b5b65c-664c-441e-8c35-ed095124e8fd.png)

**Comment by nikhilwoodruff** [comment]
Fixed with #37 - just need to add the `type` variable to the entries in `default_situation.json`.
