### ISSUE TITLE
Get working in a normal (not incognito) window

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#40]

**Comment by MaxGhenis** [comment]
This returned

**Comment by nikhilwoodruff** [comment]
@MaxGhenis I actually can't reproduce this any more, could you upload a screenshot of the error, and with F12 developer options showing the console? Thanks

**Comment by MaxGhenis** [comment]
It's OK now...nothing changed since last night?

**Comment by nikhilwoodruff** [comment]
Because it's an issue with browser caching, I'm guessing the fixes/bugs are propagated at delays specific to user devices, so seems probable that was the case here
