### ISSUE TITLE
Use policy as of the current date

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#44]
e.g. for UC

**Comment by nikhilwoodruff** [comment]
Removing from the alpha milestone for now, as we simplified to one number, but this might be expanded on later.

**Comment by nikhilwoodruff** [comment]
Ideally, we could format the results of the [simulation tracer](https://openfisca.org/doc/simulate/analyse-simulation.html) and show that. Would require [labels to be consistent](https://github.com/PSLmodels/openfisca-uk/issues/162).

**Comment by MaxGhenis** [comment]
> Removing from the alpha milestone for now, as we simplified to one number, but this might be expanded on later.

What do you mean by one number? I'm referring to the date of the policy, e.g. see also https://github.com/PSLmodels/openfisca-uk/issues/166.

**Comment by MaxGhenis** [comment]
Could we try to get this in by the video? Since we're showing the personal allowance front and center, it'd be good to have the 12,570 instead of 12,500. A hack to take 2022-01-01 is fine for now, since no policies are changing until October (AFAIK), though we'd have to comment out the October changes from the parameters.

**Comment by MaxGhenis** [comment]
Fixed in #175
