### ISSUE TITLE
URL not found when viewing situation after skipping page to enter your info

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#49]
Here's what I did:
1. Specify policy reform (10/week child UBI)
2. Skip to `Simulate on the population`
3. Click `See your results`

Then it spins for 10 seconds and gives an empty screen.

Refreshing the page (https://uk.policyengine.org/situation-results?child_UBI=10) shows this error:

![image](https://user-images.githubusercontent.com/6076111/130175652-c5bad08d-d7ca-40ec-8742-e2b2846d6d60.png)

**Comment by nikhilwoodruff** [comment]
I'm not sure about the Not Found, but I found the cause, it's an error because that exclaimation circle for the disclaimer was used without it being imported in the situation results page.
