### ISSUE TITLE
Try removing description

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#57]
The description is currently long and refers to stuff that users might not need to know, like OpenFisca (I think the disclaimers at the results page are the right place for this):
>Welcome to the UBI Center's UK Policy Engine. Powered by the open-source microsimulation model OpenFisca-UK, this site allows you to experiment with different changes to how taxes and benefits are set in the United Kingdom, and simulate the results on people, families and households in the country.

I think the four numbers actually describe it well. Could we see what it looks like if that takes up the whole first row, with no description?

**Comment by nikhilwoodruff** [comment]
How's this look?
![image](https://user-images.githubusercontent.com/35577657/130258268-577add49-b436-4ae1-8eb0-fcb33d9454f7.png)

**Comment by nikhilwoodruff** [comment]
Or this, with the full width used:
![image](https://user-images.githubusercontent.com/35577657/130258413-9359e922-e669-4651-a356-1a650ef91685.png)

**Comment by MaxGhenis** [comment]
Full width looks good to me, could you widen the text boxes too so they can fit on 2 or 3 lines?
