### ISSUE TITLE
Augment instructions

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#6]
e.g. from my experience, also needs notes on:
* `export HOST=localhost`
* Using the latest openfisca-uk-data, e.g. `openfisca-uk-data frs save ~/frs_2018.h5 2018`
* `npm start` has to be in a separate terminal
* To serve a pre-built site: `sudo npm install -g serve` and `serve -s build`

**Comment by nikhilwoodruff** [comment]
@MaxGhenis the readme has since been updated - does it answer this?
