### ISSUE TITLE
Redesign navigation flow

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#67]
Users currently navigate in two parts of the screen:
1. The upper right shows the progress

![image](https://user-images.githubusercontent.com/6076111/130309001-0938c90a-9133-4b8f-aa03-034bc0b8aaa7.png)

2. Navigation occurs in buttons below the policy "cart"

![image](https://user-images.githubusercontent.com/6076111/130309035-7324f696-dc62-4029-9378-ff87ef76f56f.png)

This was intended to act like a shopping cart flow, but given the multiple screens, I think we could streamline the interface by combining the progress tracking and navigation buttons.

Here's an example (I'm sure there's a more Ant-Designy way of doing it, especially the black to show the active screen), from the first screen ([Figma](https://www.figma.com/file/HnQkOhPRbL2L3J7Vq0C83e/PolicyEngine-flow?node-id=0%3A1)):

![image](https://user-images.githubusercontent.com/6076111/130309128-36d0950b-2fb3-41ee-9517-1e97aa03767f.png)

This also reduces the amount of text, which I think is made unnecessary by the action-oriented buttons. Here's how they could all look:

![image](https://user-images.githubusercontent.com/6076111/130308950-a63b2f6f-bb49-4070-897d-c0885e27c040.png)

@nikhilwoodruff I'm curious what you think.

**Comment by MaxGhenis** [comment]
Actually I looked through Ant Design's [navigation guide](https://ant.design/docs/spec/navigation), and I think a [top navigation](https://ant.design/docs/spec/navigation#Top-Navigation) makes sense, e.g.
![image](https://user-images.githubusercontent.com/6076111/130326512-71d53a09-08f8-49d9-ada4-2e272f5efc79.png)

Maybe this isn't descriptive enough and buttons around the shopping cart or the bottom will still be needed, but I think it's simpler than the numbered list.

**Comment by MaxGhenis** [comment]
Here's how top navigation could look on mobile ([Figma](https://www.figma.com/file/HnQkOhPRbL2L3J7Vq0C83e/PolicyEngine-flow?node-id=4%3A18)):
![image](https://user-images.githubusercontent.com/6076111/130327056-ba7d2721-513f-48eb-a40c-85458763c7aa.png)

**Comment by nikhilwoodruff** [comment]
I like this, and I think it does look better with population/situation results grouped as tabs

**Comment by nikhilwoodruff** [comment]
To use this as inspiration: https://ant.design/docs/spec/navigation#Top-Navigation
