### ISSUE TITLE
Consider writing out top-level numbers as takeaways

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#69]
Here's what the summary statistics at the top currently look like:
![Screenshot 2021-08-21 09 01 53](https://user-images.githubusercontent.com/6076111/130328101-6c81f652-4a4a-4239-9009-671e2bc91bc0.png)

This highlights the numbers well, but has a couple drawbacks IMO:
* Net cost is confusing
* Winner/loser share seems a bit awkward (I try to avoid "loser" in general)
* Could understate the connection between the number and its meaning

An alternative could be writing out the takeaways. Here's my shot at this ([Figma](https://www.figma.com/file/GeQiEpTgGUZGzPLiVZN1oA/Summary-statistics?node-id=0%3A1)):

![image](https://user-images.githubusercontent.com/6076111/130328226-be4e38c4-851e-4155-be70-81094a02c0c0.png)

Another example:
![image](https://user-images.githubusercontent.com/6076111/130328248-693ac17f-c631-49ac-ac3f-a574ada3f4fa.png)

This is still awkward in a couple ways:
* No good way I'm aware of to clearly describe the budgetary impact
* I don't think we should color the inequality change (since it's somewhat partisan), but leaving it gray makes that choice hard to hide

But I think it could be quicker for users to absorb.

**Comment by nikhilwoodruff** [comment]
Yeah I like this, and it's more consistent with the situation page. For the budgetary impact, maybe we can make it look really similar to a price tag like other websites

**Comment by MaxGhenis** [comment]
What websites have negative price tags?

**Comment by MaxGhenis** [comment]
How about instead of the budget language:
```
Reform produces £20bn net cost
Reform produces £30bn net surplus
```
It's inconsistent with the other boxes, in which the subject is something affected by the reform, but I'm stumped on better ideas.

**Comment by MaxGhenis** [comment]
We could also remove inequality from the top level summary. We've seen this confuse users since inequality can be defined in many ways, and being an outlier without a clear good/bad color is another point against showcasing it. Four boxes is probably enough, and then we can add another chart at the bottom later with the three inequality metrics we often present (Gini, top 10% share, top 1% share).

**Comment by MaxGhenis** [comment]
Combining these ideas:
![image](https://user-images.githubusercontent.com/6076111/131078625-07af7674-d2eb-4af2-bc93-a84bd41da8f5.png)
