### ISSUE TITLE
Default to reform view in individual waterfall

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#71]
e.g. I got confused why the UBI element was zero when I added a UBI, before realizing it's the baseline by default

![image](https://user-images.githubusercontent.com/6076111/130372505-a12fe9d3-044f-4f0b-a7fa-400ced2de66c.png)

Plotly has a bug such that changing the default selection doesn't change the data: https://github.com/plotly/plotly.py/issues/3276

It could be set to play automatically, but that looks to be an html export thing rather than json: https://github.com/plotly/plotly.py/issues/3332

**Comment by nikhilwoodruff** [comment]
Think we can close this, after deciding to go with the reform- rather than component- based waterfall.
