### ISSUE TITLE
Add a "include UBI in means tests" toggle option

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk-old#81]

**Comment by MaxGhenis** [comment]
I think this should be paired with a toggle to include ubi in income tax

**Comment by MaxGhenis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PolicyEngine-UK-6122e05075f9f200146e2697/issues/UBICenter/policyengine-uk/81?planning-poker) with ZenHub @nikhilwoodruff

**Comment by nikhilwoodruff** [comment]
Made the estimate higher as I'm not 100% sure on the best way for this to work with AutoUBI?

**Comment by MaxGhenis** [comment]
Let's make this issue disable AutoUBI (and vice versa). Filed #153 for them to work together.

**Comment by MaxGhenis** [comment]
Done
